---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vm-naming-template.yaml
  - vm-naming.yaml
  - vm-resource-limits-template.yaml
  - vm-resource-limits.yaml
  - vm-required-labels-template.yaml
  - vm-required-labels.yaml
