---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: VmResourceLimits
metadata:
  name: vm-resource-limits
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["kubevirt.io"]
        kinds: ["VirtualMachine"]
    namespaceSelector:
      matchLabels:
        app.kubernetes.io/part-of: virt-portal
  parameters:
    maxCpu: 8
    maxMemoryGi: 16
    maxDiskGi: 100
