---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: client
  namespace: foreman-demo
  labels:
    app: client
    app.kubernetes.io/name: client
    app.kubernetes.io/part-of: foreman-demo
    role: client
    demo: foreman-demo
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"kubevirt.io/v1","kind":"VirtualMachine","name":"foreman"}]'
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: client
        app: client
        app.kubernetes.io/name: client
        app.kubernetes.io/part-of: foreman-demo
        role: client
        demo: foreman-demo
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: client-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: client-cloudinit
  dataVolumeTemplates:
    - metadata:
        name: client-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
