---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: foreman
  namespace: foreman-demo
  labels:
    app: foreman
    app.kubernetes.io/name: foreman
    app.kubernetes.io/part-of: foreman-demo
    app.kubernetes.io/component: lifecycle-management
    app.openshift.io/runtime: redhat
    role: infra
    demo: foreman-demo
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: foreman
        app: foreman
        app.kubernetes.io/name: foreman
        app.kubernetes.io/part-of: foreman-demo
        role: infra
        demo: foreman-demo
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: rhsm-creds
              disk:
                bus: virtio
              serial: rhsm-creds
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 8Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: foreman-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: foreman-cloudinit
        - name: rhsm-creds
          secret:
            secretName: rhsm-credentials
  dataVolumeTemplates:
    - metadata:
        name: foreman-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
