apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development-policies

resources:
  - ../../base

patches:
  - target:
      kind: Policy
      name: web-terminal
    patch: |-
      - op: replace
        path: /spec/policy-templates/0/objectDefinition/spec/complianceType
        value: mustnothave
      - op: add
        path: /spec/policy-templates/0/objectDefinition/spec/removalBehavior
        value:
          clusterServiceVersions: Delete
          subscriptions: Delete
          customResourceDefinitions: Keep
          operatorGroups: DeleteIfUnused
