---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ${{ values.vmName }}
  namespace: ${{ values.environment }}
  labels:
    app: ${{ values.vmName }}
    app.kubernetes.io/name: ${{ values.vmName }}
    app.kubernetes.io/part-of: virt-portal
    app.kubernetes.io/component: vm
{%- if values.includeLabels %}
    app.kubernetes.io/managed-by: argocd
    environment: ${{ values.environment }}
    cost-center: ${{ values.costCenter }}
{%- endif %}
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: ${{ values.vmName }}
        app: ${{ values.vmName }}
        app.kubernetes.io/name: ${{ values.vmName }}
        app.kubernetes.io/part-of: virt-portal
    spec:
      domain:
        cpu:
          sockets: ${{ values.cpuCores }}
          cores: 1
          threads: 1
          maxSockets: 8
        memory:
          guest: ${{ values.memoryGi }}Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: ${{ values.vmName }}-rootdisk
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: ${{ values.vmName }}-cloudinit
  dataVolumeTemplates:
    - metadata:
        name: ${{ values.vmName }}-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: ${{ values.osImage }}
          namespace: openshift-virtualization-os-images
        storage:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: ${{ values.diskSizeGi }}Gi
