---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hybrid-app-dev

resources:
  - ../../base

nameSuffix: -dev

patches:
  - path: backend-patch.yaml
    target:
      kind: Deployment
      name: backend
  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: frontend-route-patch.yaml
    target:
      kind: Route
      name: frontend
  - path: postgresql-vm-patch.yaml
    target:
      kind: VirtualMachine
      name: postgresql-vm

# Development-specific labels
labels:
  - includeSelectors: true
    pairs:
      environment: development
