---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: postgresql-vm
spec:
  template:
    metadata:
      labels:
        demo: hybrid-cloud
        environment: development
    spec:
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 1Gi
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:40
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: postgresql-vm-cloudinit-dev
        - name: postgresql-data
          dataVolume:
            name: postgresql-vm-data-dev
