---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.sourceVm }}-netexc-${{ values.targetZone }}
  description: "Network exception: ${{ values.sourceVm }} → ${{ values.targetZone }} zone (port ${{ values.port }})"
  annotations:
    backstage.io/managed-by-location: url:https://gitlab.__BASE_DOMAIN__/vm-instances/${{ values.sourceVm }}-netexc-${{ values.targetZone }}/-/raw/main/catalog-info.yaml
    backstage.io/managed-by-origin-location: url:https://gitlab.__BASE_DOMAIN__/vm-instances/${{ values.sourceVm }}-netexc-${{ values.targetZone }}/-/raw/main/catalog-info.yaml
    argocd/app-name: vm-${{ values.sourceVm }}-netexc-${{ values.targetZone }}
    virt-portal/source-vm: ${{ values.sourceVm }}
    virt-portal/target-zone: ${{ values.targetZone }}
    virt-portal/port: "${{ values.port }}"
    virt-portal/environment: ${{ values.environment }}
    virt-portal/justification: ${{ values.justification }}
  tags:
    - network-exception
    - ${{ values.targetZone }}
    - ${{ values.environment }}
  links:
    - title: Approval MR
      url: https://gitlab.__BASE_DOMAIN__/vm-instances/${{ values.sourceVm }}-netexc-${{ values.targetZone }}/-/merge_requests/1
      icon: dashboard
    - title: Source VM
      url: https://backstage-rhdh.__BASE_DOMAIN__/catalog/default/component/${{ values.sourceVm }}
      icon: search
spec:
  type: network-exception
  lifecycle: production
  owner: ${{ values.owner }}
  system: virt-portal
