---
apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.vmName }}-cloudinit
  namespace: ${{ values.environment }}
type: Opaque
stringData:
  userdata: |
    #cloud-config
    hostname: ${{ values.vmName }}
    user: cloud-user
    password: __DEMO_PASSWORD__
    chpasswd:
      expire: false
    ssh_pwauth: true
    packages:
      - qemu-guest-agent
    runcmd:
      - systemctl enable --now qemu-guest-agent
