---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudinit-secret.yaml
  - data-pvc.yaml
  - virtualmachine.yaml
  - service.yaml
  - servicemonitor.yaml
  - vm-snapshot.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  demo: virt-portal
