quarkus.rest-client.gitlab_openapi_yaml.url=${GITLAB_URL:http://gitlab.gitlab.svc.cluster.local}/api/v4
quarkus.rest-client.notifications_openapi_yaml.url=${NOTIFICATIONS_URL:http://backstage-rhdh.rhdh.svc.cluster.local}
quarkus.openapi-generator.notifications_openapi_yaml.auth.BearerToken.bearer-token=${BACKEND_SECRET}
quarkus.tls.trust-all=true
quarkus.log.level=INFO
