---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: postgresql-vm
spec:
  template:
    spec:
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 4Gi
