---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satellite-pulp-data
  namespace: satellite-cloud-native
  labels:
    app: satellite
    app.kubernetes.io/name: satellite
    app.kubernetes.io/part-of: satellite-cloud-native
    app.kubernetes.io/component: content-management
    demo: satellite-cloud-native
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
