apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/policies/web-terminal

patches:
  - target:
      kind: Policy
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-policies
  - target:
      kind: Placement
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-policies
      - op: replace
        path: /spec/clusterSets
        value:
          - prod
  - target:
      kind: PlacementBinding
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-policies
