apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/policies/web-terminal
  - ../../../base/policies/branding

patches:
  - target:
      kind: Policy
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-policies
  - target:
      kind: Policy
      name: environment-branding
    patch: |-
      - op: replace
        path: /spec/policy-templates/0/objectDefinition/spec/object-templates/0/objectDefinition/spec/text
        value: "🔴 PRODUCTION ENVIRONMENT"
      - op: replace
        path: /spec/policy-templates/0/objectDefinition/spec/object-templates/0/objectDefinition/spec/backgroundColor
        value: "#dc291c"
  - target:
      kind: Placement
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-policies
      - op: replace
        path: /spec/clusterSets
        value:
          - prod
  - target:
      kind: PlacementBinding
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-policies
