---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.vmName }}
  description: "VM ${{ values.vmName }} (${{ values.cpuCores }} vCPU, ${{ values.memoryGi }}Gi RAM)"
  annotations:
    backstage.io/managed-by-location: url:https://gitlab.__BASE_DOMAIN__/vm-instances/${{ values.vmName }}/-/raw/main/catalog-info.yaml
    backstage.io/managed-by-origin-location: url:https://gitlab.__BASE_DOMAIN__/vm-instances/${{ values.vmName }}/-/raw/main/catalog-info.yaml
    virt-portal/cost-center: ${{ values.costCenter }}
    virt-portal/environment: ${{ values.environment }}
    virt-portal/os-image: ${{ values.osImage }}
    virt-portal/cpu-cores: "${{ values.cpuCores }}"
    virt-portal/memory-gi: "${{ values.memoryGi }}"
    virt-portal/disk-size-gi: "${{ values.diskSizeGi }}"
  tags:
    - vm
    - ${{ values.osImage }}
    - ${{ values.environment }}
  links:
    - title: OpenShift Console
      url: https://console-openshift-console.__BASE_DOMAIN__/k8s/ns/${{ values.environment }}/kubevirt.io~v1~VirtualMachine/${{ values.vmName }}
spec:
  type: vm
  lifecycle: production
  owner: ${{ values.owner }}
  system: virt-portal
