---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.vmName }}
  description: "VM ${{ values.vmName }} (${{ values.cpuCores }} vCPU, ${{ values.memoryGi }}Gi RAM)"
  annotations:
    backstage.io/managed-by-location: url:https://gitlab.__BASE_DOMAIN__/vm-instances/${{ values.vmName }}/-/raw/main/catalog-info.yaml
    backstage.io/managed-by-origin-location: url:https://gitlab.__BASE_DOMAIN__/vm-instances/${{ values.vmName }}/-/raw/main/catalog-info.yaml
    argocd/app-name: vm-${{ values.vmName }}
    orchestrator.io/workflows: '[]'
    virt-portal/cost-center: ${{ values.costCenter }}
    virt-portal/environment: ${{ values.environment }}
    virt-portal/os-image: ${{ values.osImage }}
    virt-portal/cpu-cores: "${{ values.cpuCores }}"
    virt-portal/memory-gi: "${{ values.memoryGi }}"
    virt-portal/disk-size-gi: "${{ values.diskSizeGi }}"
    virt-portal/network-zone: ${{ values.networkZone }}
  tags:
    - vm
    - ${{ values.osImage }}
    - ${{ values.environment }}
    - ${{ values.networkZone }}
  links:
    - title: Approval MR
      url: https://gitlab.__BASE_DOMAIN__/vm-instances/${{ values.vmName }}/-/merge_requests/1
      icon: dashboard
    - title: OpenShift Console
      url: https://console-openshift-console.__BASE_DOMAIN__/k8s/ns/${{ values.environment }}/kubevirt.io~v1~VirtualMachine/${{ values.vmName }}
    - title: Resize VM
      url: https://backstage-rhdh.__BASE_DOMAIN__/create/templates/default/resize-vm?formData=%7B%22vmName%22%3A%22${{ values.vmName }}%22%2C%22environment%22%3A%22${{ values.environment }}%22%2C%22osImage%22%3A%22${{ values.osImage }}%22%2C%22cpuCores%22%3A${{ values.cpuCores }}%2C%22memoryGi%22%3A${{ values.memoryGi }}%2C%22diskSizeGi%22%3A${{ values.diskSizeGi }}%2C%22networkZone%22%3A%22${{ values.networkZone }}%22%2C%22costCenter%22%3A%22${{ values.costCenter }}%22%7D
      icon: edit
    - title: Decommission VM
      url: https://backstage-rhdh.__BASE_DOMAIN__/create/templates/default/decommission-vm?formData=%7B%22vmName%22%3A%22${{ values.vmName }}%22%2C%22environment%22%3A%22${{ values.environment }}%22%7D
      icon: delete
    - title: Request Network Exception
      url: https://backstage-rhdh.__BASE_DOMAIN__/create/templates/default/network-exception?formData=%7B%22sourceVm%22%3A%22${{ values.vmName }}%22%2C%22environment%22%3A%22${{ values.environment }}%22%7D
      icon: security
spec:
  type: vm
  lifecycle: production
  owner: ${{ values.owner }}
  system: virt-portal
