---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hybrid-app-demo
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: hybrid-app
    app.kubernetes.io/component: web
    app.openshift.io/runtime: nginx
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"backend","namespace":"hybrid-app-demo"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/name: frontend
        app.kubernetes.io/part-of: hybrid-app
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: frontend
          image: quay.io/jwerak/hybrid-app-frontend:latest
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
