---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: postgresql-vm
  namespace: hybrid-app-demo
  labels:
    app: postgresql-vm
    app.kubernetes.io/name: postgresql-vm
    app.kubernetes.io/part-of: hybrid-app
    app.kubernetes.io/component: database
    app.openshift.io/runtime: postgresql
    demo: hybrid-cloud
  annotations:
    app.openshift.io/connects-to: '[]'
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: postgresql-vm
        app: postgresql-vm
        app.kubernetes.io/name: postgresql-vm
        app.kubernetes.io/part-of: hybrid-app
        app.kubernetes.io/component: database
        demo: hybrid-cloud
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: postgresql-data
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 2Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:40
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: postgresql-vm-cloudinit
        - name: postgresql-data
          dataVolume:
            name: postgresql-vm-data
