---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-vm-data
  namespace: hybrid-app-demo
  labels:
    app: postgresql-vm
    app.kubernetes.io/name: postgresql-vm
    app.kubernetes.io/part-of: hybrid-app
    app.kubernetes.io/component: database
    demo: hybrid-cloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
