---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
  namespace: rhdh
data:
  app-config.yaml: |
    app:
      title: VM Self-Service Portal
      baseUrl: https://backstage-rhdh.__BASE_DOMAIN__

    backend:
      baseUrl: https://backstage-rhdh.__BASE_DOMAIN__
      cors:
        origin: https://backstage-rhdh.__BASE_DOMAIN__
      reading:
        allow:
          - host: "gitlab.gitlab.svc.cluster.local"
          - host: "gitlab.__BASE_DOMAIN__"
      auth:
        externalAccess:
          - type: static
            options:
              token: ${BACKEND_SECRET}
              subject: external-access

    auth:
      environment: production
      session:
        secret: ${SESSION_SECRET}
      providers:
        oidc:
          production:
            metadataUrl: http://keycloak.keycloak.svc.cluster.local:8080/realms/virt-portal/.well-known/openid-configuration
            clientId: ${KEYCLOAK_CLIENT_ID}
            clientSecret: ${KEYCLOAK_CLIENT_SECRET}
            prompt: auto
            additionalScopes:
              - groups
            signIn:
              resolvers:
                - resolver: preferredUsernameMatchingUserEntityName
    signInPage: oidc

    permission:
      enabled: true
      rbac:
        admin:
          users:
            - name: user:default/platform-admin
        pluginsWithPermission:
          - catalog
          - scaffolder
          - permission
        policies-csv-file: /opt/app-root/src/rbac-policies.csv
        policyFileReload: true

    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location, Template, User, Group]
      providers:
        keycloakOrg:
          default:
            baseUrl: http://keycloak.keycloak.svc.cluster.local:8080
            loginRealm: virt-portal
            realm: virt-portal
            clientId: ${KEYCLOAK_CLIENT_ID}
            clientSecret: ${KEYCLOAK_CLIENT_SECRET}
            schedule:
              frequency: { minutes: 5 }
              timeout: { minutes: 3 }
              initialDelay: { seconds: 30 }
      locations:
        - type: url
          target: http://gitlab.gitlab.svc.cluster.local/demo/templates/-/blob/main/catalog-info.yaml
          rules:
            - allow: [Location, Template]

    argocd:
      appLocatorMethods:
        - type: config
          instances:
            - name: openshift-gitops
              url: https://openshift-gitops-server.openshift-gitops.svc.cluster.local
              username: ${ARGOCD_USERNAME}
              password: ${ARGOCD_PASSWORD}

    orchestrator:
      sonataFlowService:
        baseUrl: http://sonataflow-platform-data-index-service.rhdh.svc.cluster.local
        port: 80
        path: /graphql

    integrations:
      gitlab:
        - host: gitlab.__BASE_DOMAIN__
          token: ${GITLAB_TOKEN}
          apiBaseUrl: http://gitlab.gitlab.svc.cluster.local/api/v4
          baseUrl: https://gitlab.__BASE_DOMAIN__
        - host: gitlab.gitlab.svc.cluster.local
          token: ${GITLAB_TOKEN}
          apiBaseUrl: http://gitlab.gitlab.svc.cluster.local/api/v4
          baseUrl: http://gitlab.gitlab.svc.cluster.local
