---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
  namespace: rhdh
data:
  app-config.yaml: |
    app:
      title: VM Self-Service Portal
      baseUrl: https://backstage-rhdh.__BASE_DOMAIN__

    backend:
      baseUrl: https://backstage-rhdh.__BASE_DOMAIN__
      cors:
        origin: https://backstage-rhdh.__BASE_DOMAIN__
      reading:
        allow:
          - host: "gitlab.gitlab.svc"
          - host: "gitlab.__BASE_DOMAIN__"
      auth:
        externalAccess:
          - type: static
            options:
              token: ${BACKEND_SECRET}
              subject: external-access

    auth:
      environment: development
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true

    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location, Template]
      locations:
        - type: url
          target: https://gitlab.__BASE_DOMAIN__/demo/templates/-/blob/main/catalog-info.yaml
          rules:
            - allow: [Location, Template]

    integrations:
      gitlab:
        - host: gitlab.__BASE_DOMAIN__
          token: ${GITLAB_TOKEN}
          apiBaseUrl: https://gitlab.__BASE_DOMAIN__/api/v4
          baseUrl: https://gitlab.__BASE_DOMAIN__
