---
apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: rhdh
  namespace: rhdh
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: app-config-rhdh
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    extraFiles:
      configMaps:
        - name: rbac-policies-rhdh
    extraEnvs:
      secrets:
        - name: rhdh-secrets
      envs:
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
    route:
      enabled: true
      host: backstage-rhdh.__BASE_DOMAIN__
  flavours:
    - name: orchestrator
  database:
    enableLocalDb: true
