---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: rhdh
type: Opaque
stringData:
  BACKEND_SECRET: __BACKEND_SECRET__
  GITLAB_TOKEN: __GITLAB_TOKEN__
  SESSION_SECRET: __BACKEND_SECRET__
  KEYCLOAK_CLIENT_ID: rhdh
  KEYCLOAK_CLIENT_SECRET: __KEYCLOAK_CLIENT_SECRET__
  ARGOCD_USERNAME: admin
  ARGOCD_PASSWORD: __ARGOCD_PASSWORD__
