apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets-rbac.yaml
  - secrets-job.yaml
  - clusterset.yaml
  - clusterset-binding.yaml
  - hostedcluster.yaml
  - nodepool.yaml
