---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${{ values.vmName }}-data
  namespace: ${{ values.environment }}
  labels:
    app: ${{ values.vmName }}
    app.kubernetes.io/name: ${{ values.vmName }}
    app.kubernetes.io/part-of: virt-portal
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${{ values.diskSizeGi }}Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Block
